version: "3.8"

services:
  cashwise_postgres:
    image: postgres:15
    restart: always
    container_name: cashwise_postgres
    environment:
      POSTGRES_USER: shinodalabs
      POSTGRES_PASSWORD: shinodalabs
      POSTGRES_DB: cashwise
    volumes:
      - cashwise_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cashwise_network

  cashwise_redis:
    image: redis:7
    restart: always
    container_name: cashwise_redis
    ports:
      - "6379:6379"
    networks:
      - cashwise_network

  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    restart: always
    environment:
      - REDIS_HOSTS=local:cashwise_redis:6379
    ports:
      - "8081:8081"
    networks:
      - cashwise_network

networks:
  cashwise_network:
    driver: bridge

volumes:
  cashwise_pgdata:
